# Generated by Django 5.1 on 2024-08-24 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_app', '0003_remove_customuser_profile_pic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='legal',
            fields=[
                ('Legal_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='legal_as_Legal_id', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Case_name', models.CharField(max_length=100)),
                ('Case_description', models.TextField(null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('createdBy', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_createdBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Legal_Financial',
            fields=[
                ('Legal_Financial_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Legal_Financial_as_Legal_Financial_id', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Financial_Assests', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('liabilities', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('income_statements', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('balance_sheets', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('liquidity_ratios', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('profitability_ratios', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('createdBy', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Legal_Financial_createdBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
