# Generated by Django 5.1 on 2024-09-20 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('financial_assets', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('liquidity_ratios', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('profitability_ratios', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pat_margins', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=100)),
                ('case_description', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
