# Generated by Django 5.1 on 2024-08-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Legal_Financial_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legal',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='legal_financial',
            name='createdBy',
        ),
    ]
