# Generated by Django 5.1 on 2024-09-21 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Legal_Financial_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='financial_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='legal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='legal_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
