# Generated by Django 5.1 on 2024-09-07 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Legal_Financial_app', '0002_remove_legal_createdby_and_more'),
        ('users_app', '0003_remove_customuser_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('Financial_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Legal_Financial_as_Legal_Financial_id', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Financial_Assests', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('liquidity_ratios', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('profitability_ratios', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('PAT_margins', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Legal_Financial',
        ),
    ]
