# Generated by Django 5.1 on 2024-08-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Image_content',
            field=models.ImageField(null=True, upload_to='profile_pics/images', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Video_content',
            field=models.FileField(null=True, upload_to='profile_pics/videos', verbose_name='Videos'),
        ),
    ]
