# Generated by Django 5.1 on 2024-08-24 10:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts_app', '0002_alter_posts_image_content_alter_posts_video_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Image_content',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Video_content',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='videos'),
        ),
    ]
