# Generated by Django 5.1 on 2024-08-24 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts_app', '0003_alter_posts_image_content_alter_posts_video_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='createdBy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_createdBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
