# Generated by Django 5.1 on 2024-08-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts_app', '0004_alter_posts_createdby_alter_posts_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='createdBy',
        ),
    ]
