# Generated by Django 5.1 on 2024-08-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts_app', '0005_remove_posts_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Image_content',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Video_content',
            field=models.FileField(null=True, upload_to='videos'),
        ),
    ]
