# Generated by Django 5.1 on 2024-08-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts_app', '0006_alter_posts_image_content_alter_posts_video_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='Image_content',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='Video_content',
        ),
        migrations.AddField(
            model_name='posts',
            name='Media_url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Blobs_content',
            field=models.TextField(null=True),
        ),
    ]
