# Generated by Django 5.1 on 2024-08-20 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('website', models.URLField(blank=True)),
                ('isenterprenuer', models.BooleanField(default=False)),
                ('isinvestor', models.BooleanField(default=False)),
                ('isenthustiast', models.BooleanField(default=False)),
                ('user', models.OneToOneField(max_length=254, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
