# Generated by Django 5.1 on 2024-09-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts_apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='Blobs_content',
            new_name='blog_content',
        ),
    ]
