# Generated by Django 5.1 on 2024-09-21 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('Funding_for', models.TextField()),
                ('Amount', models.IntegerField()),
                ('Description', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('Funding_id', models.AutoField(primary_key=True, serialize=False)),
                ('Funding_RequestedBy', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Funding_RequestedBy', to=settings.AUTH_USER_MODEL)),
                ('Funding_providedBy', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Funding_providedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
