# Generated by Django 5.1 on 2024-09-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_remove_customuser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birthday',
        ),
    ]
